# Database connection URL (SQL Server VICTUS\NEWLIST, база task, вход через Windows)
spring.datasource.url=jdbc:sqlserver://localhost;instanceName=NEWLIST;databaseName=task;integratedSecurity=true;encrypt=true;trustServerCertificate=true

# JDBC driver class for SQL Server
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate settings
# Show SQL queries in the log
spring.jpa.show-sql=true

# Hibernate Dialect for SQL Server
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

# Database schema initialization strategy
spring.jpa.hibernate.ddl-auto=update
